{{- if .Values.keda.enabled -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name:  {{ include "basic-deployment.name" . }}
  labels:
    {{- include "basic-deployment.labels" . | nindent 4 }}  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment  
    name:  {{ include "basic-deployment.name" . }}
  minReplicaCount: {{ .Values.keda.minReplicaCount | default "1" }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount | default "1" }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod | default "300" }}
  pollingInterval: {{ .Values.keda.pollingInterval | default "30" }}
  triggers:
  {{- toYaml .Values.keda.triggers | nindent 4 }}
  fallback:  # Qualquer problema no seu cluster que impeça o HPA de funcionar, essa regra será ativada
    failureThreshold: {{ .Values.keda.failureThreshold | default "2" }} # Quantas vezes o HPA pode falhar antes de ativar o fallback
    replicas: {{ .Values.keda.minReplicaCount | default "1" }}  # Define a quantidade de réplicas quando a métrica não está disponível  
{{- end }}