apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orleans-hosting
  namespace: {{ include "basic-deployment.name" . }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orleans-hosting-binding
  namespace: {{ include "basic-deployment.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "basic-deployment.name" . }} 
    namespace: {{ include "basic-deployment.name" . }}
roleRef:
  kind: Role
  name: orleans-hosting
  apiGroup: rbac.authorization.k8s.io
