apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoicnNvdXphcGlwYXN0dWRpb3MiLCJwYXNzd29yZCI6ImdocF91dXRxMDZoYk9Kd1QwUUNvMHp6QUtYdzltSVJVTEc0VjNTRWgiLCJlbWFpbCI6InIuc291emFAcHJvdmlkZXJvY3AuY29tIiwiYXV0aCI6ImNuTnZkWHBoY0dsd1lYTjBkV1JwYjNNNloyaHdYM1YxZEhFd05taGlUMHAzVkRCUlEyOHdlbnBCUzFoM09XMUpVbFZNUnpSV00xTkZhQT09In19fQ==
kind: Secret
metadata:
  name: github-secret
type: kubernetes.io/dockerconfigjson